language: cpp

matrix:
  include:

  - os: linux
    addons:
      apt:
        packages:
          - libreadline-dev
          - zlib1g-dev
          - python-dev
          - python-setuptools
          - ninja-build

script:

- mkdir build
- cd build

- cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cmake --build . --target package

deploy:
  provider: releases
  api_key:
    secure: R2e3xGY1kV/D8Acr40AfKjMW3MnuQHUGRHyNClpx/kxoHAIDiZSNa1Qj11peSlhwkQj5J1FOtykJBqavufWl2h4lmGhPeMZWPa6tjN8NBXcKVLVInm568WHHLWU5NDdjnSYA5IrD76E8rOUcvRNeyL9rbMp6oz77xKo9/U8SGhgsg+r/I/tK2jwgKmDxXuKVzzQM8lFW90Qr4gO9kgxKZ0lfMtRgS+DmwVxXay0PBjmmeE7tCLRF6hnyqBX3OqW36NfVmFx1+PqxROugxarm+iDm4XshAXrCfqakc01JRm/hz8m/qK0SckAuCvv7+COKfUFoO5UzGHo3zswfFZpBTdp/wH1mzVhPZVrF7oijgF3SRIJtqx9DIkhrcWvnA4C1t1t28eOYxt8KFdbHXewQ/I+xGtIur8zUdAPNCh6wxPyhBW85fo/GkP19HlBCKPyVOkYeSwz18ramzSHdjRDKdRu0KSIY0zE+U0r0xnNciqlbN0p2h0a4RRyAEoZ46UFF3cVBpUb6GXUwZSQGRGwJSD2tWD4ItDCRw+892fJDtiFP9rqs3uUgZuvlKo4xrmcfzP4/vAWfBTL317/ItcZbwNk7LIk3eTmyLzS1MkY4SMZxq4S6ELc/1ahalsCz/EDKu8z/nitmcpZ1vWGrhXhI1C0hTFtqwvoFmkPQkYHsifM=
  skip_cleanup: true
  file_glob: true
  file:
    - super_prove-*.tar.gz
  on:
    repo: sterin/super-prove-build
    tags: true
